### ISSUE TITLE
Clojure Script Support

### ISSUE THREAD

**Issue by xjunior** [amalloy/ordered#23]
Please, add clojure script support.

**Comment by amalloy** [comment]
I don't plan to. It's just a pain to maintain two codebases, and cljc files do not look very pleasant to me. I'd have to duplicate a lot of code to work as closely with the JS interpreter as I currently do with the JVM.

If you want a CLJS ordered map, https://github.com/frankiesardo/linked looks like it copied a lot of `ordered`, and added CLJS support.
