### ISSUE TITLE
.hashCode of ordered maps with nil keys or values NPEs

### ISSUE THREAD

**Issue by lvh** [amalloy/ordered#27]
I honestly do not know if this is a bug in timbre or in flatland, so I'm filing an issue with each. 

Timbre issue: https://github.com/ptaoussanis/timbre/issues/187

**Comment by lvh** [comment]
I've figured out what's going on: `.hashCode` doesn't work if a key or value is nil.

```
(.hashCode (ordered-map [[nil nil]]))
;; NullPointerException   flatland.ordered.map.OrderedMap/fn--28038 (map.clj:90)
```

**Comment by lvh** [comment]
The bug is on this line: https://github.com/amalloy/ordered/blob/develop/src/flatland/ordered/map.clj#L90

Context:

```clojure
  (hashCode [this]
    (reduce (fn [acc ^MapEntry e]
              (let [k (.key e), v (.val e)]
                (unchecked-add ^Integer acc ^Integer (bit-xor (.hashCode k) (.hashCode v)))))
0 (.seq this)))
```

Either `(.hashCode k)` or `(.hashCode v)` will raise the exception. Looks like that should be `or`d with 0 or something. Would you be interested in a PR?

**Comment by arrdem** [comment]
Sure!

**Comment by lvh** [comment]
Cool, #28 is up.

**Comment by lewang** [comment]
@arrdem any chance you can expedite cutting a release from #28  ?
