### ISSUE TITLE
Equivalence doesn't take order into account for ordered-map

### ISSUE THREAD

**Issue by erp12** [amalloy/ordered#35]
Not sure if this is the desired behavior or not. See code snippet below.

```clj
(def m1 (ordered-map :a 1 :b 2))
(def m2 (ordered-map :b 2 :a 1))
(= m1 m2)
;; true
```

The easy work around is to wrap both maps in something like `vec` or `seq`.

```clj
(def m1 (ordered-map :a 1 :b 2))
(def m2 (ordered-map :b 2 :a 1))
(= (vec m1) (vec m2))
;; false
```

**Comment by jafingerhut** [comment]
I believe the behavior in your first code snippet _is_ the expected behavior.  It is the same behavior as when using `=` to compare Clojure's built-in hash maps (no key sorting semantics) against its built-in sorted maps, which is: two maps are equal if they have the same set of (key, value) pairs.

**Comment by erp12** [comment]
Ok thank you, that clears things up. I wasn't really sure what the correct behavior to expect was, and your explanation makes sense to me.
